### ISSUE TITLE
SHA1 for ghcjs-0.2.1?

### ISSUE THREAD

**Issue by mmaz** [tolysz/spock-ghcjs-sample#2]
Hi, thank you for providing a patched version of GHCJS for stack! I tried fetching the tarball and ran into a hash mismatch:

``` bash
$ stack --stack-yaml=stack-frontend.yaml setup
...
ghcjs-0.2.1.9007001_ghc-8.0.1:   11.27 MiB downloaded...Download expectation failure: content hash (SHA1)
Expected: e640724883238593e2d2f7f03991cb413ec0347b (ByteString)
Actual:   "838d58502bdaff55d38627e371eba5ebf9ab5923"
```

Locally, I seem to observe the same mismatch that stack reports:

``` bash
$ curl -O http://tolysz.org/ghcjs/untested/ghc-8.0-2016-09-26-lts-7.1-9007001-mem.tar.gz
$ openssl sha1 ghc-8.0-2016-09-26-lts-7.1-9007001-mem.tar.gz 
SHA1(ghc-8.0-2016-09-26-lts-7.1-9007001-mem.tar.gz)= 838d58502bdaff55d38627e371eba5ebf9ab5923
```

Suggestions? Thanks again!

**Comment by tolysz** [comment]
Apologies ;)
the location:
http://tolysz.org/ghcjs/untested/ghc-8.0-2016-09-26-lts-7.1-9007001-mem.tar.gz
is generated via cron
~~try change it tohttp://tolysz.org/ghcjs/ghc-8.0-2016-09-26-lts-7.1-9007001-mem.tar.gz~~
~~As it should match the posted one~~
~~So you can either remove the hash or try the url without the 'untested'.~~
I updated the repo. (and copied over the exact version)  - should work now.

**Comment by mmaz** [comment]
Thanks for the help! That fixed it for me!
